# Generated by Django 5.2.17 on 2026-08-20 04:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('districts', '0001_initial'),
        ('operations', '0001_initial'),
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_type', models.CharField(choices=[('p50_travel', 'P50 travel time'), ('p90_travel', 'P90 travel time'), ('late_classifier', 'Late arrival classifier')], max_length=40)),
                ('version', models.CharField(max_length=40)),
                ('file_path', models.CharField(max_length=500)),
                ('feature_schema', models.JSONField(default=list)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('training_data_description', models.TextField(default='Synthetic fictional school-morning segments. Not real student or operational data.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_synthetic', models.BooleanField(default=True)),
                ('trained_at', models.DateTimeField(blank=True, null=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_artifacts', to='districts.district')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('segment_ref', models.CharField(blank=True, max_length=120)),
                ('feature_payload', models.JSONField(default=dict)),
                ('prediction', models.JSONField(default=dict)),
                ('actual_result', models.JSONField(blank=True, null=True)),
                ('model_artifact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to='machine_learning.modelartifact')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routing.route')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.trip')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
