# Generated by Django 5.2.17 on 2026-08-20 04:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('districts', '0001_initial'),
        ('transportation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_type', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('message', models.CharField(blank=True, max_length=400)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.JSONField(blank=True, default=dict)),
                ('related_id', models.UUIDField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='districts.district')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoutePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('academic_term', models.CharField(default='2026-2027', max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generating', 'Generating'), ('generated', 'Generated'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('optimization_mode', models.CharField(choices=[('fastest', 'Fastest'), ('balanced', 'Balanced'), ('reliability', 'Reliability')], default='balanced', max_length=20)),
                ('objective_weights', models.JSONField(blank=True, default=dict)),
                ('aggregate_metrics', models.JSONField(blank=True, default=dict)),
                ('solver_metadata', models.JSONField(blank=True, default=dict)),
                ('infeasibility', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('job_id', models.UUIDField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='districts.district')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_plans', to='districts.school')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('route_code', models.CharField(max_length=40)),
                ('direction', models.CharField(choices=[('am', 'Morning'), ('pm', 'Afternoon')], default='am', max_length=8)),
                ('scheduled_start', models.TimeField(blank=True, null=True)),
                ('scheduled_school_arrival', models.TimeField(blank=True, null=True)),
                ('total_distance_km', models.FloatField(default=0)),
                ('p50_duration_seconds', models.PositiveIntegerField(default=0)),
                ('p90_duration_seconds', models.PositiveIntegerField(default=0)),
                ('on_time_probability', models.FloatField(default=0)),
                ('risk_score', models.FloatField(default=0)),
                ('capacity_utilization', models.FloatField(default=0)),
                ('risk_factors', models.JSONField(blank=True, default=list)),
                ('student_count', models.PositiveIntegerField(default=0)),
                ('wheelchair_count', models.PositiveIntegerField(default=0)),
                ('assigned_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='transportation.driverprofile')),
                ('assigned_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='transportation.vehicle')),
                ('depot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='districts.depot')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='districts.school')),
                ('route_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='routing.routeplan')),
            ],
            options={
                'ordering': ['route_code'],
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField()),
                ('kind', models.CharField(default='stop', max_length=16)),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('scheduled_arrival', models.TimeField(blank=True, null=True)),
                ('scheduled_departure', models.TimeField(blank=True, null=True)),
                ('predicted_p50_arrival', models.TimeField(blank=True, null=True)),
                ('predicted_p90_arrival', models.TimeField(blank=True, null=True)),
                ('student_count', models.PositiveIntegerField(default=0)),
                ('cumulative_load', models.PositiveIntegerField(default=0)),
                ('distance_from_previous_km', models.FloatField(default=0)),
                ('expected_seconds_from_previous', models.PositiveIntegerField(default=0)),
                ('bus_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transportation.busstop')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='routing.route')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('route', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='RouteStopStudent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('board', 'Board'), ('alight', 'Alight')], default='board', max_length=12)),
                ('route_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='routing.routestop')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_assignments', to='transportation.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TravelMatrixCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cache_key', models.CharField(max_length=128)),
                ('provider', models.CharField(max_length=40)),
                ('payload', models.JSONField(default=dict)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='districts.district')),
            ],
            options={
                'unique_together': {('district', 'cache_key')},
            },
        ),
    ]
