# Generated by Django 5.2.17 on 2026-09-11 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='safety_context',
            field=models.JSONField(blank=True, default=dict, help_text='High-injury corridor overlap, active construction, signal crossings, snow-route coverage from the real Louisville Metro / LOJIC open-data layers (apps.geodata).'),
        ),
    ]
