# Generated by Django 5.2.17 on 2026-09-11 23:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionPermit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_id', models.CharField(max_length=60, unique=True)),
                ('source', models.CharField(choices=[('current', 'Currently issued'), ('historical', 'Historical')], default='current', max_length=12)),
                ('permit_no', models.CharField(blank=True, max_length=60)),
                ('applicant_name', models.CharField(blank=True, max_length=200)),
                ('work_type', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('street_address', models.CharField(blank=True, max_length=300)),
                ('from_date', models.DateTimeField(blank=True, null=True)),
                ('to_date', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='geodata_con_latitud_2bc9d9_idx'), models.Index(fields=['from_date', 'to_date'], name='geodata_con_from_da_af5215_idx')],
            },
        ),
        migrations.CreateModel(
            name='HighInjurySegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_id', models.CharField(max_length=60, unique=True)),
                ('road_name', models.CharField(blank=True, max_length=200)),
                ('corridor_name', models.CharField(blank=True, max_length=200)),
                ('core_class', models.CharField(blank=True, max_length=80)),
                ('priority_rank', models.FloatField(blank=True, help_text='Lower is higher priority per LOJIC PRIORITY_R.', null=True)),
                ('total_epdo', models.FloatField(blank=True, null=True)),
                ('total_ka_crashes', models.FloatField(blank=True, help_text='Killed/serious-injury crash count.', null=True)),
                ('length_miles', models.FloatField(blank=True, null=True)),
                ('owner', models.CharField(blank=True, max_length=120)),
                ('midpoint_lat', models.FloatField()),
                ('midpoint_lng', models.FloatField()),
                ('geometry', models.JSONField(blank=True, default=list)),
            ],
            options={
                'indexes': [models.Index(fields=['midpoint_lat', 'midpoint_lng'], name='geodata_hig_midpoin_23fe06_idx')],
            },
        ),
        migrations.CreateModel(
            name='MidblockCrossing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_id', models.CharField(max_length=60, unique=True)),
                ('road_name', models.CharField(blank=True, max_length=200)),
                ('cross_street', models.CharField(blank=True, max_length=200)),
                ('crossing_type', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(blank=True, max_length=80)),
                ('has_rrfb_or_signal', models.BooleanField(default=False)),
                ('near_tarc_stop', models.BooleanField(default=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='geodata_mid_latitud_3b30ed_idx')],
            },
        ),
        migrations.CreateModel(
            name='PublicSchoolSite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_id', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('level', models.CharField(blank=True, max_length=20)),
                ('loc_type', models.CharField(blank=True, max_length=40)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=4)),
                ('zip_code', models.CharField(blank=True, max_length=12)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('abbreviation', models.CharField(blank=True, max_length=40)),
                ('website', models.CharField(blank=True, max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='geodata_pub_latitud_71752f_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoadSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_id', models.CharField(max_length=60, unique=True)),
                ('road_name', models.CharField(blank=True, max_length=200)),
                ('core_class', models.CharField(blank=True, max_length=80)),
                ('context_class', models.CharField(blank=True, max_length=20)),
                ('speed_limit_mph', models.PositiveIntegerField(blank=True, null=True)),
                ('road_category', models.PositiveSmallIntegerField(default=0, help_text='0=local/collector, 1=minor arterial, 2=major arterial — matches ML training encoding.')),
                ('urban_density', models.FloatField(default=0.5, help_text='0=rural (C1) .. 1=urban core (C6), derived from CONTEXT_CLASS.')),
                ('midpoint_lat', models.FloatField()),
                ('midpoint_lng', models.FloatField()),
                ('geometry', models.JSONField(blank=True, default=list, help_text='[[lng, lat], ...]')),
            ],
            options={
                'indexes': [models.Index(fields=['midpoint_lat', 'midpoint_lng'], name='geodata_roa_midpoin_a9262d_idx')],
            },
        ),
        migrations.CreateModel(
            name='SnowRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_id', models.CharField(max_length=60, unique=True)),
                ('road_name', models.CharField(blank=True, max_length=200)),
                ('route', models.CharField(blank=True, max_length=40)),
                ('response', models.CharField(blank=True, max_length=40)),
                ('priority', models.CharField(blank=True, max_length=20)),
                ('state_owned', models.BooleanField(default=False)),
                ('midpoint_lat', models.FloatField()),
                ('midpoint_lng', models.FloatField()),
                ('geometry', models.JSONField(blank=True, default=list)),
            ],
            options={
                'indexes': [models.Index(fields=['midpoint_lat', 'midpoint_lng'], name='geodata_sno_midpoin_0c594c_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrafficSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_id', models.CharField(max_length=60, unique=True)),
                ('main_street', models.CharField(blank=True, max_length=200)),
                ('cross_street', models.CharField(blank=True, max_length=200)),
                ('owner', models.CharField(blank=True, max_length=120)),
                ('route', models.CharField(blank=True, max_length=120)),
                ('signal_type', models.CharField(blank=True, max_length=120)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='geodata_tra_latitud_ef2f0a_idx')],
            },
        ),
    ]
