# Generated by Django 5.2.17 on 2026-09-11 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geodata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='highinjurysegment',
            options={'ordering': ['source_id']},
        ),
        migrations.AlterModelOptions(
            name='midblockcrossing',
            options={'ordering': ['source_id']},
        ),
        migrations.AlterModelOptions(
            name='roadsegment',
            options={'ordering': ['source_id']},
        ),
        migrations.AlterModelOptions(
            name='snowroute',
            options={'ordering': ['source_id']},
        ),
        migrations.AlterModelOptions(
            name='trafficsignal',
            options={'ordering': ['source_id']},
        ),
    ]
