# Generated by Django 5.2.17 on 2026-08-20 04:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('districts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('stop_code', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=300)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('is_approved', models.BooleanField(default=True)),
                ('accessibility', models.CharField(blank=True, max_length=80)),
                ('safety_notes', models.TextField(blank=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='districts.district')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('district', 'stop_code')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.CharField(max_length=40)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('grade', models.CharField(max_length=8)),
                ('home_address', models.CharField(max_length=300)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('eligibility', models.CharField(choices=[('eligible', 'Eligible'), ('ineligible', 'Ineligible'), ('conditional', 'Conditional')], default='eligible', max_length=20)),
                ('accessibility_notes', models.TextField(blank=True)),
                ('requires_wheelchair', models.BooleanField(default=False)),
                ('max_ride_time_override_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='districts.district')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='districts.school')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'unique_together': {('district', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_id', models.CharField(max_length=40)),
                ('license_expiration', models.DateField(blank=True, null=True)),
                ('endorsements', models.JSONField(blank=True, default=list)),
                ('availability', models.CharField(default='weekday_am', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='districts.district')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('district', 'employee_id')},
            },
        ),
        migrations.CreateModel(
            name='StudentStopAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('am', 'Morning'), ('pm', 'Afternoon'), ('both', 'Both')], default='am', max_length=8)),
                ('walking_distance_m', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('bus_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_assignments', to='transportation.busstop')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_assignments', to='transportation.student')),
            ],
            options={
                'unique_together': {('student', 'bus_stop', 'direction')},
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internal_number', models.CharField(max_length=40)),
                ('license_plate', models.CharField(max_length=20)),
                ('capacity', models.PositiveIntegerField()),
                ('wheelchair_capacity', models.PositiveIntegerField(default=0)),
                ('vehicle_type', models.CharField(choices=[('standard', 'Standard'), ('accessible', 'Accessible'), ('activity', 'Activity')], default='standard', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('spare', 'Spare'), ('maintenance', 'Maintenance'), ('retired', 'Retired')], default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('depot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='districts.depot')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='districts.district')),
            ],
            options={
                'ordering': ['internal_number'],
                'unique_together': {('district', 'internal_number')},
            },
        ),
    ]
