# Generated by Django 5.2.17 on 2026-09-12 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='busstop',
            name='safety_flags',
            field=models.JSONField(blank=True, default=dict, help_text='Auto-computed from Louisville Metro/LOJIC open data (apps.geodata): high-injury-corridor proximity and whether a marked crossing or signal is nearby. Recomputed on every save.'),
        ),
    ]
