# Generated by Django 5.2.17 on 2026-08-20 04:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('districts', '0001_initial'),
        ('routing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StressTestRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('n_simulations', models.PositiveIntegerField(default=750)),
                ('traffic_severity', models.FloatField(default=0.4)),
                ('weather_severity', models.FloatField(default=0.2)),
                ('rain', models.BooleanField(default=False)),
                ('starting_delay_min', models.IntegerField(default=0)),
                ('starting_delay_max', models.IntegerField(default=8)),
                ('boarding_variability', models.FloatField(default=0.3)),
                ('driver_absence_rate', models.FloatField(default=0.02)),
                ('road_disruption_rate', models.FloatField(default=0.05)),
                ('results', models.JSONField(blank=True, default=dict)),
                ('interpretation', models.TextField(blank=True)),
                ('compare_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stress_tests_as_compare', to='routing.routeplan')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='districts.district')),
                ('route_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stress_tests', to='routing.routeplan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
