# Generated by Django 5.2.17 on 2026-09-12 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stresstestrun',
            name='snow_day',
            field=models.BooleanField(default=False, help_text='Extra penalty for routes with low real snow-route coverage (Route.safety_context.snow_route_coverage).'),
        ),
    ]
