# Generated by Django 5.2.17 on 2026-08-20 04:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('state', models.CharField(default='KY', max_length=2)),
                ('timezone', models.CharField(default='America/Kentucky/Louisville', max_length=64)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('opens_at', models.TimeField(blank=True, null=True)),
                ('closes_at', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='districts.district')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DistrictPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_walking_distance_m', models.JSONField(default=dict, help_text='{"elementary": 400, "middle": 600, "high": 800}')),
                ('max_student_ride_minutes', models.PositiveIntegerField(default=45)),
                ('min_arrival_buffer_minutes', models.PositiveIntegerField(default=10)),
                ('default_boarding_seconds', models.PositiveIntegerField(default=20)),
                ('wheelchair_boarding_seconds', models.PositiveIntegerField(default=90)),
                ('allowable_early_minutes', models.PositiveIntegerField(default=20)),
                ('allowable_late_minutes', models.PositiveIntegerField(default=0)),
                ('reliability_target', models.FloatField(default=0.9)),
                ('extra_constraints', models.JSONField(blank=True, default=dict)),
                ('district', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='districts.district')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('school_code', models.CharField(max_length=40)),
                ('school_type', models.CharField(choices=[('elementary', 'Elementary'), ('middle', 'Middle'), ('high', 'High')], max_length=20)),
                ('address', models.CharField(max_length=300)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('morning_bell_time', models.TimeField()),
                ('dismissal_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='districts.district')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('district', 'school_code')},
            },
        ),
    ]
