# Generated by Django 5.2.17 on 2026-08-20 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('transportation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardianstudentlink',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_links', to='transportation.student'),
        ),
        migrations.AlterUniqueTogether(
            name='guardianstudentlink',
            unique_together={('guardian', 'student')},
        ),
    ]
