# Generated by Django 5.2.17 on 2026-08-20 04:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('districts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_type', models.CharField(choices=[('schools', 'Schools'), ('students', 'Students'), ('drivers', 'Drivers'), ('vehicles', 'Vehicles'), ('stops', 'Stops')], max_length=20)),
                ('original_filename', models.CharField(max_length=255)),
                ('stored_path', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('mapped', 'Mapped'), ('validated', 'Validated'), ('committed', 'Committed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('proposed_column_mapping', models.JSONField(blank=True, default=dict)),
                ('confirmed_column_mapping', models.JSONField(blank=True, default=dict)),
                ('validation_results', models.JSONField(blank=True, default=dict)),
                ('preview_rows', models.JSONField(blank=True, default=list)),
                ('headers', models.JSONField(blank=True, default=list)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('invalid_rows', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='districts.district')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImportRowError',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_number', models.PositiveIntegerField()),
                ('field', models.CharField(blank=True, max_length=80)),
                ('error_code', models.CharField(max_length=40)),
                ('message', models.CharField(max_length=400)),
                ('raw_row', models.JSONField(default=dict)),
                ('import_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='row_errors', to='imports.importjob')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
